### ISSUE TITLE
haplodmf.sh cannot be run from any folder

### ISSUE THREAD

**Issue by RolandFaure** [dhcai21/HaploDMF#2]
Hello,

I was trying to run HaploDMF, and I ran across this issue:

```
/home/rfaure/Documents/software/HaploDMF/haplodmf.sh -r ncbi.fasta -i hs/tmp/reads_on_asm.sam -o haploDMF
count nucleotide occurrence
python: can't open file '/home/rfaure/Documents/these/HairSplitter/species/viruses/HCV/./src/count_frequency.py': [Errno 2] No such file or directory
SNV detection
python: can't open file '/home/rfaure/Documents/these/HairSplitter/species/viruses/HCV/./src/two_binomial.py': [Errno 2] No such file or directory
/home/rfaure/Documents/software/HaploDMF/haplodmf.sh: line 483: haploDMF/haplodmf_snv.txt: No such file or directory
python: can't open file '/home/rfaure/Documents/these/HairSplitter/species/viruses/HCV/./src/out_haplotypes.py': [Errno 2] No such file or directory
python: can't open file '/home/rfaure/Documents/these/HairSplitter/species/viruses/HCV/./src/extract_reads.py': [Errno 2] No such file or directory
python: can't open file '/home/rfaure/Documents/these/HairSplitter/species/viruses/HCV/./src/run_medaka.py': [Errno 2] No such file or directory
```
HaploDMF is clearly looking for the python files in the wrong places. Now I'm running HaploDMF from the folder of haplodmf.sh and it seems to run fine (finger crossed :smile: )

Probably a problem in the way the python files are called, but maybe I missed an instruction somewhere ?

**Comment by dhcai21** [comment]
Hello,

Thank you for taking the time to report this issue. Regarding running HaploDMF, executing the program from the folder containing the "src" is needed. This requirement is due to the usage of a local path in the code. By checking the "haplodmf.sh" file, you will observe that the command "python ./src/xxxx.py" is utilized. Therefore, running HaploDMF from the corresponding folder is necessary for proper execution. I will consider optimizing this in the future.

If you have any questions or encounter difficulties while using HaploDMF, please don't hesitate to contact me via GitHub or email at "dhcai2-c@my.cityu.edu.hk." I assure you that I will respond to your inquiries as soon as possible.

Best,
Dehan
